stages:
  - build

build-executable-host:
  stage: build
  image: node:22-bookworm
  variables:
    BUN_INSTALL: "$CI_PROJECT_DIR/.bun"
  rules:
    - when: manual
      allow_failure: true
  before_script:
    - curl -fsSL https://bun.sh/install | bash
    - export PATH="$BUN_INSTALL/bin:$PATH"
    - npm ci
  script:
    - export PATH="$BUN_INSTALL/bin:$PATH"
    - npm run build:exe
    - ls -lh dist-bin/
  artifacts:
    paths:
      - dist-bin/
    expire_in: 7 days

include:
  - component: $CI_SERVER_FQDN/s3w/cicd/common/publish-sftp@2.0.0-alpha
    inputs:
      stage: "deploy"
      allow_failure: false
      required_artifacts: ["build-executable-host"]
      server: "sftp://s3w.stc-spb.ru"
      paths: |
        dist-bin/gcl-ui-linux-x64:/storage/cicd/gcl-ui/
      login: $SFTP_LOGIN
