import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import pty from "node-pty";
import { projectDir } from "./util.js";

// Debug mode: we re-create the job's shell session ourselves (shell executor
// semantics) so we can pause between script steps. At a breakpoint the very
// same shell that is executing the job turns interactive — `read -e` +
// `eval` inside the job shell — so every variable and function of the job is
// inspectable and mutable. Step/breakpoint events ride on a private OSC
// escape sequence (number 7770) that terminals ignore but the server parses.

const OSC_RE = /\x1b\]7770;([^\x07\x1b]*)(?:\x07|\x1b\\)/g;

function shq(s) {
  return "'" + String(s).replace(/'/g, "'\\''") + "'";
}

function buildDriver({ jobName, cwd, variables, steps, breakpoints }) {
  const bp = new Set(breakpoints);
  const L = [];
  L.push("#!/usr/bin/env bash");
  L.push("# generated by gcl-ui debug mode");
  L.push('__gcl_osc() { printf \'\\033]7770;%s\\007\' "$1"; }');
  L.push(`__gcl_break() {
  __gcl_osc "break=$1"
  printf '\\n\\033[1;35m● paused at %s\\033[0m\\n' "$1"
  printf '\\033[2m  this shell IS the job shell — inspect/change variables freely\\033[0m\\n'
  printf '\\033[2m  :c continue · :q abort job · anything else runs in job context\\033[0m\\n'
  local __cmd
  while true; do
    if ! read -e -r -p $'\\001\\033[1;35m\\002debug ▸ \\001\\033[0m\\002' __cmd; then echo; break; fi
    history -s -- "$__cmd" 2>/dev/null
    case "$__cmd" in
      :c|:cont|:continue) break ;;
      :q|:quit|:abort) __gcl_osc "abort=$1"; exit 130 ;;
      '') ;;
      *) eval "$__cmd" ;;
    esac
  done
  __gcl_osc "resume=$1"
}`);
  L.push("");
  for (const [k, v] of Object.entries(variables)) {
    L.push(`export ${k}=${shq(v)}`);
  }
  L.push(`cd ${shq(cwd)}`);
  L.push("set -o pipefail");
  L.push("");

  // each step becomes a function so multi-line steps stay intact while
  // still running in the top-level shell (variables persist across steps)
  steps.forEach((step, i) => {
    L.push(`__gcl_step_${i}() {`);
    L.push(step.text);
    L.push("}");
  });
  L.push("");

  steps.forEach((step, i) => {
    const id = step.id;
    L.push(`__gcl_osc "step=${id}"`);
    if (bp.has(id)) L.push(`__gcl_break ${shq(id)}`);
    for (const line of step.text.split("\n")) {
      L.push(`printf '\\033[32m$ %s\\033[0m\\n' ${shq(line)}`);
    }
    L.push(`__gcl_step_${i}`);
    L.push(`__rc=$?`);
    L.push(`if [ "$__rc" -ne 0 ]; then`);
    L.push(`  __gcl_osc "steprc=${id},$__rc"`);
    L.push(
      `  printf '\\n\\033[1;31m✗ step failed (exit %s)\\033[0m \\033[2m— job shell kept alive for inspection; :c runs the next step anyway, :q aborts\\033[0m\\n' "$__rc"`
    );
    L.push(`  __gcl_break ${shq(id + " (failed)")}`);
    L.push(`fi`);
    L.push("");
  });
  L.push('__gcl_osc "done=0"');
  L.push(`printf '\\n\\033[1;32m✓ job script finished\\033[0m\\n'`);
  L.push("exit 0");
  return L.join("\n") + "\n";
}

export class DebugManager {
  constructor(cwd, broadcast) {
    this.cwd = cwd;
    this.broadcast = broadcast;
    this.sessions = new Map();
  }

  list() {
    return [...this.sessions.values()].map((s) => this.summary(s));
  }

  summary(s) {
    return {
      id: s.id,
      job: s.job,
      status: s.status,
      currentStep: s.currentStep,
      pausedAt: s.pausedAt,
      breakpoints: s.breakpoints,
      createdAt: s.createdAt,
      exitCode: s.exitCode,
    };
  }

  // job: pipeline job object; breakpoints: array of step ids ("script:1")
  start({ job, breakpoints = [], variables = {}, cols = 120, rows = 30 }) {
    const steps = [];
    for (const [section, list] of [
      ["before_script", job.beforeScript || []],
      ["script", job.script || []],
    ]) {
      list.forEach((text, i) => steps.push({ id: `${section}:${i}`, text }));
    }
    if (!steps.length) throw new Error(`job ${job.name} has no script to debug`);

    // precedence (weakest → strongest): CI defaults, yaml variables
    // (global+job, merged by the client), user stores / session overrides
    const vars = {
      CI: "true",
      GITLAB_CI: "false",
      GCL_UI_DEBUG: "1",
      CI_PROJECT_DIR: this.cwd,
      CI_JOB_NAME: job.name,
      CI_JOB_STAGE: job.stage,
      ...(job.variables || {}),
      ...variables,
    };

    const id = crypto.randomBytes(5).toString("hex");
    const dir = path.join(projectDir(this.cwd), "tmp");
    fs.mkdirSync(dir, { recursive: true });
    const scriptFile = path.join(dir, `debug-${id}.sh`);
    fs.writeFileSync(scriptFile, buildDriver({ jobName: job.name, cwd: this.cwd, variables: vars, steps, breakpoints }), {
      mode: 0o700,
    });

    const term = pty.spawn("bash", [scriptFile], {
      name: "xterm-256color",
      cols,
      rows,
      cwd: this.cwd,
      env: { ...process.env, TERM: "xterm-256color" },
    });

    const session = {
      id,
      job: job.name,
      steps,
      breakpoints,
      status: "running",
      currentStep: null,
      pausedAt: null,
      createdAt: Date.now(),
      exitCode: null,
      term,
      scriptFile,
      oscTail: "",
      scrollback: [],
      scrollbackSize: 0,
      totalBytes: 0,
    };
    this.sessions.set(id, session);

    term.onData((data) => {
      const offset = session.totalBytes;
      session.totalBytes += data.length;
      session.scrollback.push(data);
      session.scrollbackSize += data.length;
      while (session.scrollbackSize > 2_000_000 && session.scrollback.length > 1) {
        session.scrollbackSize -= session.scrollback.shift().length;
      }
      this.parseOsc(session, data);
      this.broadcast({ type: "debug.data", sessionId: id, data, offset });
    });
    term.onExit(({ exitCode }) => {
      session.status = exitCode === 0 ? "finished" : exitCode === 130 ? "aborted" : "failed";
      session.exitCode = exitCode;
      session.pausedAt = null;
      this.broadcast({ type: "debug.update", session: this.summary(session) });
      fs.rm(scriptFile, { force: true }, () => {});
    });

    this.broadcast({ type: "debug.update", session: this.summary(session) });
    return this.summary(session);
  }

  parseOsc(session, data) {
    const text = session.oscTail + data;
    session.oscTail = text.slice(-128);
    OSC_RE.lastIndex = 0;
    let m;
    let changed = false;
    while ((m = OSC_RE.exec(text))) {
      const [key, value] = m[1].split("=");
      if (key === "step") {
        session.currentStep = value;
        session.pausedAt = null;
        changed = true;
      } else if (key === "break") {
        session.pausedAt = value;
        session.status = "paused";
        changed = true;
      } else if (key === "resume") {
        session.pausedAt = null;
        session.status = "running";
        changed = true;
      } else if (key === "done") {
        session.currentStep = null;
        changed = true;
      }
    }
    // avoid re-parsing the same escapes when they sit inside the kept tail
    session.oscTail = session.oscTail.replace(OSC_RE, "");
    if (changed) this.broadcast({ type: "debug.update", session: this.summary(session) });
  }

  input(id, data) {
    this.sessions.get(id)?.term.write(data);
  }

  resize(id, cols, rows) {
    try {
      this.sessions.get(id)?.term.resize(cols, rows);
    } catch {}
  }

  continue(id) {
    const s = this.sessions.get(id);
    if (s && s.status === "paused") s.term.write(":c\r");
  }

  abort(id) {
    const s = this.sessions.get(id);
    if (!s) return;
    if (s.status === "paused") s.term.write(":q\r");
    else {
      try {
        s.term.kill("SIGKILL");
      } catch {}
    }
  }

  // returns the buffered output plus the absolute byte offset of its end,
  // so clients can drop live chunks that are already included
  scrollback(id) {
    const s = this.sessions.get(id);
    if (!s) return { data: "", end: 0 };
    return { data: s.scrollback.join(""), end: s.totalBytes };
  }

  dispose(id) {
    const s = this.sessions.get(id);
    if (!s) return;
    try {
      s.term.kill("SIGKILL");
    } catch {}
    this.sessions.delete(id);
  }
}
