// Encode web/dist into server/embedded-assets.js so a packaged binary can serve
// the UI from memory. Usage: node scripts/embed-assets.mjs [--clear]
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const distDir = path.join(root, "web", "dist");
const outFile = path.join(root, "server", "embedded-assets.js");

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".map": "application/json; charset=utf-8",
};

if (process.argv.includes("--clear")) {
  fs.writeFileSync(
    outFile,
    "// Populated at package time by scripts/embed-assets.mjs with the built web/dist\n" +
      "// encoded as base64, so a single-file executable can serve the UI from memory\n" +
      "// with no files on disk. Empty in the source tree (the dev/disk path is used).\n" +
      "export const assets = {};\n"
  );
  console.log("embedded-assets.js cleared");
  process.exit(0);
}

if (!fs.existsSync(path.join(distDir, "index.html"))) {
  console.error("web/dist not built — run `npm run build` first");
  process.exit(1);
}

const entries = {};
let total = 0;
function walk(dir, rel) {
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const r = rel ? rel + "/" + name : name;
    const st = fs.statSync(full);
    if (st.isDirectory()) walk(full, r);
    else {
      const buf = fs.readFileSync(full);
      total += buf.length;
      entries["/" + r] = {
        type: MIME[path.extname(name).toLowerCase()] || "application/octet-stream",
        b64: buf.toString("base64"),
      };
    }
  }
}
walk(distDir, "");

const body =
  "// AUTO-GENERATED by scripts/embed-assets.mjs — do not edit.\n" +
  "export const assets = " +
  JSON.stringify(entries) +
  ";\n";
fs.writeFileSync(outFile, body);
console.log(`embedded ${Object.keys(entries).length} files (${(total / 1024).toFixed(0)} KB) into embedded-assets.js`);
